### ISSUE TITLE
homo-anime が iOS 9 上で動作しない

### ISSUE THREAD

**Issue by chitoku-k** [chitoku-k/HomoChecker#12]
## 状況

iOS 9 上の Safafi で `homo-anime` のアニメーションがスタートしない。`homo-anime` 要素の class が `start` に変更されない。

## 原因

`Observable.prototype.repeat()` を呼び出すと動作しなくなる模様。詳細不明。

https://github.com/chitoku-k/HomoChecker/blob/0808e873de5f54f1ae52b590beb6649b563c1ea8/client/src/tags/homo-anime.tag#L171-L186

**Comment by hexium310** [comment]
Android 7.0でも動きません
